# NPU monitor parameter
NPU_WIDTH:int = 8
TEMP_WIDTH:int = 10
POWER_WIDTH:int = 10
AICORE_WIDTH:int = 16
HBM_WIDTH:int = 15

# Process monitor parameter
NPU_ID_WIDTH:int = 6
PID_WIDTH:int = 8
NAME_WIDTH:int = 15
MEM_WIDTH:int = 18
CMD_WIDTH:int = 100
BAR_WIDTH:int = 60
PROCESS_WIDTH:int = NPU_ID_WIDTH + PID_WIDTH + NAME_WIDTH + MEM_WIDTH + CMD_WIDTH + BAR_WIDTH
